force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJobRequest__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Specifies the number of records to process in each batch, allowing fine control over job execution volume.</description>
    <inlineHelpText>Defines the batch size for processing records. The maximum is 200 records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Captures any error messages in case of job failure.</description>
    <inlineHelpText>Increments each time the job is retried due to failure.</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>Provides a unique, readable identifier for each job request, making it easier to locate and track jobs.</description>
    <inlineHelpText>A descriptive name for the batch job, useful for tracking and identification.</inlineHelpText>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test/BatchJobProcessorTest.cls
@IsTest
public with sharing class BatchJobProcessorTest {
	
	@TestSetup
	static void makeData(){
		AsyncJobRequestService.instance.setBypass();

		insert new AsyncJobRequest__c(
			RecordTypeId = AsyncJobRequestConstants.recordType.BatchableId,
			JobName__c = MockBatchableJob.class.getName(),
			BatchSize__c = 200
		);
	}

	@IsTest
	static void testExecuteJobPositive(){

		List<AsyncJobRequest__c> jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Pending.name()
		);
		Assert.areEqual(0, jobRequests.size(), 'There should not be any Async Job Requests in status Pending.');

		Test.startTest();

		new BatchJobProcessor().executeJob();
		jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Pending.name()
		);

		Test.stopTest();
		
		Assert.areEqual(1, jobRequests.size(), 'There should be a Async Job Requests in status Pending.');
		Assert.isNotNull(jobRequests.get(0).JobId__c, 'The Job Id field has to be specified.');
	}

	@IsTest
	static void testExecuteJobNegative(){
		List<AsyncJobRequest__c> jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		);
		jobRequests.get(0).JobName__c = 'IncorrectJobName';
		AsyncJobRequestService.instance.setBypass();
		update jobRequests;

		jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Failed.name()
		);
		Assert.areEqual(0, jobRequests.size(), 'There should not be any Async Job Requests in status Failed.');

		Test.startTest();

		new BatchJobProcessor().executeJob();
		jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Failed.name()
		);

		Test.stopTest();
		
		Assert.areEqual(1, jobRequests.size(), 'There should be a Async Job Requests in status Failed.');
		Assert.isNull(jobRequests.get(0).JobId__c, 'The Job Id field has to be specified.');
		Assert.isNotNull(jobRequests.get(0).ErrorMessage__c, 'The Error Message field has to be specified.');
	}
}