force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJobRequest__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Specifies the number of records to process in each batch, allowing fine control over job execution volume.</description>
    <inlineHelpText>Defines the batch size for processing records. The maximum is 200 records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>Provides a unique, readable identifier for each job request, making it easier to locate and track jobs.</description>
    <inlineHelpText>A descriptive name for the batch job, useful for tracking and identification.</inlineHelpText>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>A flexible field for passing serialized data (such as JSON) to the batch job, allowing customized parameters without adding more fields.</description>
    <inlineHelpText>Stores additional data or parameters required for this batch job. Use JSON format to structure complex data.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/recordTypes/Batchable.recordType-meta.xml
<RecordType>
    <fullName>Batchable</fullName>
    <active>true</active>
    <label>Batchable</label>
</RecordType>

force-app/main/default/objects/AsyncJobRequest__c/recordTypes/Queueable.recordType-meta.xml
<RecordType>
    <fullName>Queueable</fullName>
    <active>true</active>
    <label>Queueable</label>
</RecordType>

demo-app/main/default/classes/AsyncJobRequestScheduler.cls
public class AsyncJobRequestScheduler implements Schedulable {
	
	private Integer numberOfJobs;
	private Integer rescheduleMinutes;
	
	public AsyncJobRequestScheduler() {
		this.numberOfJobs = 100;
		this.rescheduleMinutes = 2;
	}
	
	public AsyncJobRequestScheduler(Integer numberOfJobs, Integer rescheduleMinutes) {
		this.numberOfJobs = numberOfJobs;
		this.rescheduleMinutes = rescheduleMinutes;
	}
	
	public void execute(SchedulableContext ctx) {
		createAsyncJobRequests();
		if (ctx != null) {
			System.abortJob(ctx.getTriggerId());
		}
		scheduleJob(rescheduleMinutes);
	}
	
	private void createAsyncJobRequests() {
		List<AsyncJobRequest__c> jobRequests = new List<AsyncJobRequest__c>();
		for (Integer i = 0; i < numberOfJobs; i++) {
			jobRequests.add(
				new AsyncJobRequest__c(
					RecordTypeId = AsyncJobRequestConstants.recordType.QueueableId,
					JobName__c = TestQueueable.class.getName(),
					Payload__c = 'Something in the queueable payload...'
				)
			);
			jobRequests.add(
				new AsyncJobRequest__c(
					RecordTypeId = AsyncJobRequestConstants.recordType.BatchableId,
					JobName__c = TestBatch.class.getName(),
					BatchSize__c = 200,
					Payload__c = 'Something in the batchable payload...'
				)
			);
		}
		insert jobRequests;
	}
	
	public static Id scheduleJob(Integer initialDelayMinutes) {
		return System.schedule(
			AsyncJobRequestScheduler.class.getName()+ '-' + Datetime.now().getTime(),
			Datetime.now().addMinutes(initialDelayMinutes).format('0 m H d M ? y'),
			new AsyncJobRequestScheduler()
		);
	}
}