force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJobRequest__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Captures any error messages in case of job failure.</description>
    <inlineHelpText>Increments each time the job is retried due to failure.</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/FinishedTime__c.field-meta.xml
<CustomField>
    <fullName>FinishedTime__c</fullName>
    <description>The date and time when the batch job finished processing.</description>
    <inlineHelpText>Stores the completion time of the batch job, updated when the job status changes to Completed or Failed.</inlineHelpText>
    <label>Finished Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <description>Tracks the lifecycle state of the job, from initial request to completion, and assists in managing retries and error handling.</description>
    <inlineHelpText>The current status of the Async Job Request.</inlineHelpText>
    <label>Job Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/ProcessedTime__c.field-meta.xml
<CustomField>
    <fullName>ProcessedTime__c</fullName>
    <description>Indicates when the job started processing, helping to analyze and optimize processing times.</description>
    <inlineHelpText>The date and time when this job began processing.</inlineHelpText>
    <label>Processed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/RequestedTime__c.field-meta.xml
<CustomField>
    <fullName>RequestedTime__c</fullName>
    <description>Captures when each job request was submitted, assisting in job scheduling and load balancing.</description>
    <inlineHelpText>The date and time when this job request was created.</inlineHelpText>
    <label>Requested Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AsyncJobRequest.cls
public with sharing class AsyncJobRequest {
	private AsyncJobRequest__c asyncJobRequest;

	public AsyncJobRequest(AsyncJobRequest__c asyncJobRequest) {
		this.asyncJobRequest = asyncJobRequest;
	}

	public AsyncJobRequest__c record() {
		return this.asyncJobRequest;
	}

	public AsyncJobRequest setJobId(Id jobId) {
		asyncJobRequest.JobId__c = jobId;
		return this;
	}

	public AsyncJobRequest setJobStatus(AsyncJob.ChangeStatusPayload changeStatusPayload) {
		asyncJobRequest.JobStatus__c = changeStatusPayload.status.name();
		switch on changeStatusPayload.status {
			when Pending {
				asyncJobRequest.RequestedTime__c = changeStatusPayload.changedDatetime;
			}
			when Processing {
				asyncJobRequest.ProcessedTime__c = changeStatusPayload.changedDatetime;
			}
			when Completed {
				asyncJobRequest.FinishedTime__c = changeStatusPayload.changedDatetime;
			}
		}
		return this;
	}

	public AsyncJobRequest addErrorMessage(Exception exc) {
		String errorMessage = String.format(
			AsyncJobRequestConstants.ERROR_TMPL,
			new List<String>{exc.getMessage(), exc.getStackTraceString()}
		);
		this.addErrorMessage(errorMessage);
		return this;
	}

	public AsyncJobRequest addErrorMessage(String errorMessage) {
		if (this.asyncJobRequest.ErrorMessage__c == null) {
			this.asyncJobRequest.ErrorMessage__c = errorMessage;
		} else {
			this.asyncJobRequest.ErrorMessage__c += errorMessage;
		}
		return this;
	}

	public AsyncJobRequest updateRecord() {
		update this.asyncJobRequest;
		return this;
	}
}