force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJobRequest__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Specifies the number of records to process in each batch, allowing fine control over job execution volume.</description>
    <inlineHelpText>Defines the batch size for processing records. The maximum is 200 records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>Provides a unique, readable identifier for each job request, making it easier to locate and track jobs.</description>
    <inlineHelpText>A descriptive name for the batch job, useful for tracking and identification.</inlineHelpText>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test/ChangeStatusJobEventHandlerTest.cls
@IsTest
public with sharing class ChangeStatusJobEventHandlerTest {

	@TestSetup
	static void makeData() {
		AsyncJobRequestService.instance.setBypass();
		insert new AsyncJobRequest__c(
			RecordTypeId = AsyncJobRequestConstants.recordType.BatchableId,
			JobName__c = BatchJobProcessorTestBatchableJob.class.getName(),
			JobId__c = new FakeId(AsyncApexJob.sObjectType).getFakeId(),
			BatchSize__c = 200
		);
	}

	@IsTest
	static void testHandleChangeStatusEventNotFinalStatus() {
		List<AsyncJobRequest__c> jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		);
		Assert.areEqual(1, jobRequests.size(), 'There should be one Async Job Request in status Waiting.');

		Test.startTest();

		new ChangeStatusJobEventHandler().handleEvent(
			new AsyncJob().createJobChangeStatusEvent(
				AsyncJobRequestConstants.JobStatus.Processing,
				jobRequests.get(0).JobId__c
			)
		);

		Test.stopTest();

		jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Processing.name()
		);

		Assert.areEqual(1, jobRequests.size(), 'There should be one Async Job Request in status Processing.');
		Assert.isNotNull(jobRequests.get(0).JobId__c, 'The Job Id field should not be null.');
	}

	@IsTest
	static void testHandleChangeStatusEventFinalStatus() {
		AsyncJobRequestService.instance.setBypass();
		insert new AsyncJobRequest__c(
			RecordTypeId = AsyncJobRequestConstants.recordType.BatchableId,
			JobName__c = BatchJobProcessorTestBatchableJob.class.getName(),
			JobId__c = new FakeId(AsyncApexJob.sObjectType).getFakeId(),
			BatchSize__c = 200
		);

		List<AsyncJobRequest__c> jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		);
		Assert.areEqual(2, jobRequests.size(), 'There should be two Async Job Requests in status Waiting.');

		Test.startTest();

		new ChangeStatusJobEventHandler().handleEvent(
			new AsyncJob().createJobChangeStatusEvent(
				AsyncJobRequestConstants.JobStatus.Completed,
				jobRequests.get(0).JobId__c
			)
		);

		Test.stopTest();

		jobRequests = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		);

		Assert.areEqual(0, jobRequests.size(), 'There should be no Async Job Requests in status Waiting.');
	}
}