force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The field represents the action type.</description>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__e/fields/JobRequestTypeId__c.field-meta.xml
<CustomField>
    <fullName>JobRequestTypeId__c</fullName>
    <description>Represents the Record Type Id of Async Job Request record.</description>
    <label>Job Request Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AsyncJobRequestService.cls
/**
 * @description Service class for handling AsyncJobRequest operations.
 *              Implements a singleton pattern and provides methods to publish job events.
 */
public class AsyncJobRequestService {

	private Boolean bypass = false;
	
	@TestVisible
	public static AsyncJobRequestService instance {
		get{
			if (instance == null) {
				instance = new AsyncJobRequestService();
			}
			return instance;
		}
		private set;
	}

	/**
	 * @description Publishes queue job events for the provided AsyncJobRequest records.
	 * @param asyncJobRequests List of AsyncJobRequest__c records to process.
	 * @return List of Database.SaveResult objects with publishing results
	 */
	public List<Database.SaveResult> publishQueueJobEvents(List<AsyncJobRequest__c> asyncJobRequests) {
		if (bypass) {
			return new List<Database.SaveResult>();
		}
		List<AsyncJob__e> jobEvents = new List<AsyncJob__e>();
		for (AsyncJobRequest__c jobRequestRecord : new AsyncJobRequestDistributor(asyncJobRequests).getNewAsyncJobRequests()) {
			jobEvents.add(new AsyncJob__e(
				Action__c = AsyncJobEventConstants.Action.QUEUE_JOB.name(),
				JobRequestTypeId__c = jobRequestRecord.RecordTypeId
			));
		}
		if (!jobEvents.isEmpty()) {
			return EventBus.publish(jobEvents);
		}
		return new List<Database.SaveResult>();
	}

	/**
	 * @description Enables bypass mode to skip publishing job events.
	 * @return The current instance of AsyncJobRequestService.
	 */
	@TestVisible
	private AsyncJobRequestService setBypass() {
		this.bypass = true;
		return this;
	}

	/**
	 * @description Disables bypass mode to allow publishing job events.
	 * @return The current instance of AsyncJobRequestService.
	 */
	@TestVisible
	private AsyncJobRequestService unsetBypass() {
		this.bypass = false;
		return this;
	}
}