force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The field represents the action type.</description>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AsyncJobEventService.cls
public with sharing class AsyncJobEventService {
	public static AsyncJobEventService instance {
		get{
			if (instance == null) {
				instance = new AsyncJobEventService();
			}
			return instance;
		}
		set;
	}

	private Map<AsyncJobEventConstants.Action, IAsyncJobEventHandler> asyncJobEventHandlers = new Map<AsyncJobEventConstants.Action, IAsyncJobEventHandler>{
		AsyncJobEventConstants.Action.ADD_ERROR => new ErrorJobEventHandler(),
		AsyncJobEventConstants.Action.CHANGE_STATUS => new ChangeStatusJobEventHandler(),
		AsyncJobEventConstants.Action.QUEUE_JOB => new QueueJobEventHandler()
	};

	public void handleEvent(AsyncJob__e event) {
		IAsyncJobEventHandler handler = this.asyncJobEventHandlers.get(AsyncJobEventConstants.Action.valueOf(event.Action__c));
		handler.handleEvent(event);
	}
}