force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The field represents the action type.</description>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__e/fields/AsyncJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncJobId__c</fullName>
    <description>Represents the Batchable or Queueable job Id</description>
    <label>Async Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/AsyncJobRequest__c.object-meta.xml
<CustomObject>
    <description>A custom object designed to queue and manage Batch Apex job requests for optimized load balancing and system resource utilization.</description>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>BJR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJobRequest__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Specifies the number of records to process in each batch, allowing fine control over job execution volume.</description>
    <inlineHelpText>Defines the batch size for processing records. The maximum is 200 records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Captures any error messages in case of job failure.</description>
    <inlineHelpText>Increments each time the job is retried due to failure.</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the associated Apex batch job. Used for updating to prevent duplicate entries.</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>Provides a unique, readable identifier for each job request, making it easier to locate and track jobs.</description>
    <inlineHelpText>A descriptive name for the batch job, useful for tracking and identification.</inlineHelpText>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <description>Tracks the lifecycle state of the job, from initial request to completion, and assists in managing retries and error handling.</description>
    <inlineHelpText>The current status of the Async Job Request.</inlineHelpText>
    <label>Job Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AsyncJobRequest__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>A flexible field for passing serialized data (such as JSON) to the batch job, allowing customized parameters without adding more fields.</description>
    <inlineHelpText>Stores additional data or parameters required for this batch job. Use JSON format to structure complex data.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/test/ErrorJobEventHandlerTest.cls
@IsTest
public with sharing class ErrorJobEventHandlerTest {
	
	@TestSetup
	static void makeData() {
		AsyncJobRequestService.instance.setBypass();
		insert new AsyncJobRequest__c(
			RecordTypeId = AsyncJobRequestConstants.recordType.BatchableId,
			JobName__c = 'TestBatchJob',
			JobId__c = new FakeId(AsyncApexJob.SObjectType).getFakeId(),
			BatchSize__c = 200,
			JobStatus__c = AsyncJobRequestConstants.JobStatus.Waiting.name()
		);
	}
	
	@IsTest
	static void testHandleErrorEvent() {
		AsyncJobRequest__c jobRequest = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		).get(0);
		Assert.isNull(jobRequest.ErrorMessage__c, 'Error message should be null initially');
		
		String errorPayload = 'Test error message';
		AsyncJob__e errorEvent = new AsyncJob__e(
			Action__c = AsyncJobEventConstants.Action.ADD_ERROR.name(),
			AsyncJobId__c = jobRequest.JobId__c,
			Payload__c = errorPayload
		);
		
		Test.startTest();
		new ErrorJobEventHandler().handleEvent(errorEvent);
		Test.stopTest();
		
		jobRequest = AsyncJobRequestSelector.instance.getById(jobRequest.Id);
		
		Assert.areEqual(errorPayload, jobRequest.ErrorMessage__c, 'Error message should be updated');
	}
	
	@IsTest
	static void testHandleMultipleErrorEvents() {
		AsyncJobRequest__c jobRequest = AsyncJobRequestSelector.instance.getByJobStatus(
			AsyncJobRequestConstants.JobStatus.Waiting.name()
		).get(0);
		
		String firstErrorPayload = 'First error message';
		AsyncJob__e firstErrorEvent = new AsyncJob__e(
			Action__c = AsyncJobEventConstants.Action.ADD_ERROR.name(),
			AsyncJobId__c = jobRequest.JobId__c,
			Payload__c = firstErrorPayload
		);
		
		String secondErrorPayload = 'Second error message';
		AsyncJob__e secondErrorEvent = new AsyncJob__e(
			Action__c = AsyncJobEventConstants.Action.ADD_ERROR.name(),
			AsyncJobId__c = jobRequest.JobId__c,
			Payload__c = secondErrorPayload
		);
		
		Test.startTest();
		new ErrorJobEventHandler().handleEvent(firstErrorEvent);
		
		new ErrorJobEventHandler().handleEvent(secondErrorEvent);
		Test.stopTest();
		
		jobRequest = AsyncJobRequestSelector.instance.getById(jobRequest.Id);
		Assert.isTrue(jobRequest.ErrorMessage__c.contains(firstErrorPayload), 'Error message should contain first error');
		Assert.isTrue(jobRequest.ErrorMessage__c.contains(secondErrorPayload), 'Error message should contain second error');
	}
}