force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/JobRequestTypeId__c.field-meta.xml
<CustomField>
    <fullName>JobRequestTypeId__c</fullName>
    <description>Represents the Record Type Id of Async Job Request record.</description>
    <label>Job Request Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueueJobEventHandler.cls
public with sharing class QueueJobEventHandler implements IAsyncJobEventHandler {
	private Map<Id, IAsyncJobExecutor> recordTypeToProcessorMap = new Map<Id, IAsyncJobExecutor>{
		AsyncJobRequestConstants.recordType.BatchableId => new BatchableJobProcessor(),
		AsyncJobRequestConstants.recordType.QueueableId => new QueueableJobProcessor()
	};

	public void handleEvent(AsyncJob__e event) {
		IAsyncJobExecutor jobExecutor = this.recordTypeToProcessorMap.get(event.JobRequestTypeId__c);
		jobExecutor.executeJob();
	}
}