force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The field represents the action type.</description>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__e/fields/AsyncJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncJobId__c</fullName>
    <description>Represents the Batchable or Queueable job Id</description>
    <label>Async Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__e/fields/JobRequestTypeId__c.field-meta.xml
<CustomField>
    <fullName>JobRequestTypeId__c</fullName>
    <description>Represents the Record Type Id of Async Job Request record.</description>
    <label>Job Request Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangeStatusJobEventHandler.cls
public with sharing class ChangeStatusJobEventHandler implements IAsyncJobEventHandler {
	private List<AsyncJobRequestConstants.JobStatus> completedStatuses = new List<AsyncJobRequestConstants.JobStatus>{
		AsyncJobRequestConstants.JobStatus.Completed,
		AsyncJobRequestConstants.JobStatus.Failed
	};

	public void handleEvent(AsyncJob__e event) {
		AsyncJobRequest asyncJobRequest = new AsyncJobRequest(
			AsyncJobRequestSelector.instance.getByJobId(event.AsyncJobId__c)
		);
		AsyncJobRequestConstants.JobStatus jobStatus = AsyncJobRequestConstants.JobStatus.valueOf(event.Payload__c);
		asyncJobRequest
			.setJobStatus(jobStatus)
			.updateRecord();
		if (completedStatuses.contains(jobStatus)) {
			EventBus.publish(new AsyncJob__e(
				Action__c = AsyncJobEventConstants.Action.QUEUE_JOB.name(),
				JobRequestTypeId__c = AsyncJobRequestConstants.recordType.BatchableId
			));
		}
	}
}