force-app/main/default/objects/AsyncJob__e/AsyncJob__e.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <pluralLabel>Async Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJob__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The field represents the action type.</description>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__e/fields/AsyncJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncJobId__c</fullName>
    <description>Represents the Batchable or Queueable job Id</description>
    <label>Async Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AsyncJob.cls
public with sharing virtual class AsyncJob {
	
	public AsyncJob__e createJobErrorEvent(Exception exc, Id asyncJobId) {
		String errorMessage = String.format(
			AsyncJobRequestConstants.ERROR_TMPL,
			new List<String>{exc.getMessage(), exc.getStackTraceString()}
		);
		return new AsyncJob__e(
			Action__c = AsyncJobEventConstants.Action.ADD_ERROR.name(),
			AsyncJobId__c = asyncJobId,
			Payload__c = errorMessage
		);
	}

	public AsyncJob__e createJobChangeStatusEvent(AsyncJobRequestConstants.JobStatus status, Id asyncJobId) {
		return new AsyncJob__e(
			Action__c = AsyncJobEventConstants.Action.CHANGE_STATUS.name(),
			AsyncJobId__c = asyncJobId,
			Payload__c = status.name()
		);
	}
}